---
- name: Include preflight setup tasks
  include_tasks: "common/preflight.yml"
  tags:
    - preflight

- name: Include common installation tasks
  include_tasks: "common/install.yml"
  tags:
    - install

- name: Include OS and distribution specific installation tasks.
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}/install.yml"
        - "{{ ansible_os_family|lower }}/install.yml"
      skip: true
  tags:
    - install

- name: Render geth client toml configuration
  include_tasks: "common/config.yml"
  tags:
    - config

- name: Start Geth client and RPC service
  include_tasks: "common/launch.yml"
  tags:
    - launch
